# Generated by Django 5.2.4 on 2025-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lost_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.TextField()),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('location', models.CharField(max_length=255)),
                ('date_lost', models.DateField()),
                ('contact_info', models.CharField(max_length=100)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
