# Generated by Django 5.2.4 on 2025-09-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_lost_reports_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_reports',
            old_name='contact_info',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='lost_reports',
            old_name='item_desc',
            new_name='item_description',
        ),
    ]
