# Generated by Django 5.2.4 on 2025-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_contact_info_lost_reports_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost_reports',
            name='item_description',
            field=models.TextField(),
        ),
    ]
