# Generated by Django 5.2.4 on 2025-09-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_lost_reports_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost_reports',
            name='user',
        ),
    ]
