# Generated by Django 5.2.4 on 2025-09-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_found_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claimed_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=100)),
                ('claimant_contact', models.CharField(max_length=100)),
                ('claim_description', models.TextField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.found_reports')),
            ],
        ),
    ]
