# Generated by Django 5.2.4 on 2025-10-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_claimed_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimed_items',
            old_name='claimant_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='claimed_items',
            old_name='claim_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='claimed_items',
            old_name='claimant_name',
            new_name='name',
        ),
    ]
