# Generated by Django 5.2.4 on 2025-10-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_claimant_contact_claimed_items_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimed_items',
            name='item_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
