# Generated by Django 5.2.4 on 2025-10-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_claimed_items_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimed_items',
            name='claim_status',
            field=models.BooleanField(default=False),
        ),
    ]
