# Generated by Django 5.2.4 on 2025-10-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_claimed_items_claim_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found_reports',
            old_name='date_lost',
            new_name='found_date',
        ),
    ]
