# Generated by Django 5.2.4 on 2025-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_rename_date_lost_found_reports_found_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_reports',
            name='category',
            field=models.CharField(default='others', max_length=100),
        ),
        migrations.AddField(
            model_name='lost_reports',
            name='category',
            field=models.CharField(default='others', max_length=100),
        ),
    ]
