# Generated by Django 5.2.4 on 2025-10-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_found_reports_category_lost_reports_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_reports',
            old_name='date_lost',
            new_name='lost_date',
        ),
    ]
