# Generated by Django 5.2.4 on 2025-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_rename_date_lost_lost_reports_lost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimed_items',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
